[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 115200

upload_port = COM5
monitor_port = COM5

build_flags =
    -DBSEC_DEBUG_LEVEL=0
    
lib_deps =
    adafruit/Adafruit BME680 Library 
    adafruit/Adafruit Unified Sensor
    adafruit/Adafruit BusIO
    adafruit/Adafruit MPU6050
    mikalhart/TinyGPSPlus
    sandeepmistry/LoRa